source 'https://rubygems.org'

gem 'sinatra', '~> 2.0'
gem 'sinatra-activerecord', '~> 2.0'
gem 'activerecord', '~> 4.0'
gem 'activesupport', '~> 4.2'
gem 'activemodel', '~> 4.2'
gem 'state_machines-activerecord', '~> 0.5'
gem 'gitlab', '~> 4.5.0'
gem 'cocoapods'#, '~> 1.5'
gem 'pg', '~> 0.21.0'

# gem 'sqlite3'
# gem 'cocoapods-external-pod-sorter'
gem 'member_reminder'
gem 'rake'
gem 'git'