require_relative './routes/deploys'
require_relative './routes/webhook'
require_relative './routes/oauth'
require_relative './routes/operations'
require_relative './routes/ci'
require_relative './routes/tools'