# port: 9797
port: 8080
host: '0.0.0.0'

redis_port: 6379
redis_db: 0

websocket_port: 8081

log_file: '~/.labor/labor.log'
sidekiq_log_file: '~/.labor/sidekiq.log'
gitlab_endpoint: 'http://git.2dfire-inc.com/api/v4'

# RestBuild's token
gitlab_private_token: 'Se79zS8rgUupDZv6JN8G'
gitlab_http_timeout: 20

# 删除已存在 tag
allow_delete_tag_when_already_existed: false

# 不需要负责人在 mr 上进行 code review 时设置成 true
reviewed_merge_request_when_created: true

# 私有源 ssh
cocoapods_private_source_url: 'git@git.2dfire-inc.com:ios/cocoapods-spec.git'
# main_deploy: 

# pod_deploy:
#   create_mr_only_not_merged: true