# port: 9797
port: 8080
host: '0.0.0.0'

# domain: 'labor-labor.app.2dfire.com'
# redis_host: redis-persistent
# redis_port: 6379
# redis_db: 0
# redis_password: ik1BxmTPSCcLc4ll

redis_host: localhost
redis_port: 6379
redis_db: 0
redis_password: 

labor_app_url: http://labor-app-labor.app.2dfire.com

websocket_service_url: 'http://labor-socket-server-labor.app.2dfire.com'
# websocket_service_url: 'http://localhost:8081'

log_file: '~/.labor/labor.log'
sidekiq_log_file: '~/.labor/sidekiq.log'
gitlab_endpoint: 'http://git.2dfire.net/api/v4'
# 私有源 ssh
cocoapods_private_source_url: 'git@git.2dfire.net:ios/cocoapods-spec.git'
cocoapods_third_party_group: 'cocoapods-repos'

# RestBuild's token
gitlab_private_token: 'Se79zS8rgUupDZv6JN8G'
gitlab_http_timeout: 20

# 删除非当前发布中已存在 tag
allow_delete_tag_when_already_existed: false

# 不需要负责人在 mr 上进行 code review 时设置成 true
reviewed_merge_request_when_created: true

# 创建 mr 时是否需要通知 owner
remind_owner_when_merge_request_created: false
