#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 40
  timeout: 5000

development:
  <<: *default
  database: labor_development
  username: postgres
  password: daimao

production: 
  <<: *default
  database: labor_production
  username: postgres
  password: daimao