#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 40
  timeout: 5000

development:
  <<: *default
  database: labor_development
  username: postgres
  password: daimao

# local test
# production: 
#   <<: *default
#   database: labor_production
#   username: postgres
#   password: daimao
#   host: localhost

# openshift postgresql
#'10.136.42.65'
production: 
  <<: *default
  database: labor
  username: labor
  password: 2Dfire.com
  host: 10.136.42.65
  # host: postgresql-labor.app.2dfire.com