#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 40
  timeout: 5000

development:
  <<: *default
  database: labor_development
  username: postgres
  password: daimao

# local test
# production: 
#   <<: *default
#   database: labor_production
#   username: postgres
#   password: daimao
  # host: localhostd

# openshift postgresql
production: 
  <<: *default
  database: defaultdb
  username: admin
  password: ajdhfiuh29hfsdhif
  host: '10.136.42.65'